iovisor/ply

src/lang/ast.c

First thanks for this project! I had some trouble setting it up due to my broken linux headers, but in the end I got it working.
I found this very minor thing in the code. You probably wanted to undefine the previously defined `OP`

Correctly undefine used macro

---

scripts/opensnoop.ply

I think /scripts is a nice example directory of short examples like this, but with a few more features we might want a /tools directory as well that has documented (man page & examples file) tools with arguments. Such tools are going to get verbose fast, once they have command line options (which might mean wrapping in shell).
This particular example documents the missing features with the issue numbers, which I think helps newcomers learn why something is the way it is (because it's pending a fix).

add initial opensnoop

---

configure.ac
src/Makefile.am
src/arch/arch-aarch64.c

This commit is to add support for ARM aarch64 architecture.  It adds
building options for @host_cpu is 'aarch64' and add CPU registers
related functions.
Have tested the scripts execsnoop.ply & opensnoop.ply on 96boards Hikey
with ARMv8 CA53 CPUs.
Signed-off-by: Leo Yan <leo.yan@linaro.org>

arch: Support for aarch64

---

man/ply.1.ronn
oneliners.md
src/pvdr/kprobe.c

profile events are enabled via PERF_TYPE_SOFTWARE/PERF_COUNT_SW_CPU_CLOCK
perf event and we use a kprobe firing - perf_swevent_hrtimer() - to catch
the profile events in kernel context.  Profiling on all CPUs and per-CPU
profiling are both supported; see the manual page for details on the
syntax. Admittedly a bit of a hack but thought I'd point at it just in case it's useful.
Thanks!
Signed-off-by: Alan Maguire <alan.maguire@oracle.com>

profile provider support

---

src/kallsyms.c

As far as I can tell there is an implicit assumption in the code that
/proc/kallsyms information is sorted from low address to high already.
I don't see that on my system (OEL7.4 plus 4.14.7 kernel). For example:
./ply -c 'kprobe:ip_local_deliver {@c[stack()].count(); }'
1 probe active
^Cde-activating probes
@c:
ip_local_deliver+0x1
ip_rcv+0x2ea
__netif_receive_skb_core+0x3dc
__netif_receive_skb+0x18
netif_receive_skb_internal+0x45
napi_gro_receive+0xd5
<ffffffffa0b5e5e4>
<ffffffffa0b60a14>
<ffffffffa0b62df6>
<ffffffffa0b63ac3>
<ffffffffa0a17ec8>
<ffffffffa0a11c0a>
strp_mod_exit+0x1e7099cd
strp_mod_exit+0x1e70b25a
irq_thread_fn+0x1e
irq_thread+0x13c           6
We see that a number of addresses were not resolved. The reason
appears to lie in the implicit assumption of sorting; bsearch …

some kernel function symbols not being resolved when printing stacks

---

src/include/ply/ply.h
src/ply.c
src/pvdr/kprobe.c

these changes use a more targeted approach in enabling/disabling probes.
When enabling k[ret]probes we use the current pid to make the probe unique
system-wide; this allows multiple instances of ply to run.  Also remove
global enable/disable of kprobes/tracepoints as it is not needed.
Signed-off-by: Alan Maguire <alan.maguire@oracle.com>

fix issue #16: don't enable all tracepoints

---

oneliners.md
scripts/syscall-fail.ply
src/lang/lex.l
src/lang/parse.y

a probe predicate is defined as an expr in parse.y; however
exprs can contain '/' division symbols, which are also used
to bracket a predicate.  This causes a shift-reduce conflict
for flex, but we can resolve it by having a '/' followed by
a '{' resolve to a CLOSEPRED token while other instances of '/'
resolve to a DIV token.  This change allows us to define probe
predicates without having to use parentheses, e.g. in
syscall-fail.ply.
Signed-off-by: Alan Maguire <alan.maguire@oracle.com>

parens should not be required for probe predicates

---

man/ply.1.ronn
src/pvdr/kprobe.c

u[ret]probes of form
uprobe:/usr/bin/bash:0x2fbd0
uretprobe:/usr/bin/bash:0x2fbd0
...where 0x2fbd0 is address of a function.  Future work will hopefully
add symbol resolution.
Signed-off-by: Alan Maguire <alan.maguire@oracle.com>

basic u[ret]probe support

---

src/Makefile.am

When build ply on ARM64, the variable 'host_cpu' is aarch64 and the
makefile uses it so set kernel build environment variable
'ARCH=aarch64', this results in the kernel header installation reports
failure due it cannot find path '$kernel/arch/aarch64'.
The reason for this failure is kernel places ARM64 architecture code in
'$kernel/arch/arm64' but not '$kernel/arch/aarch64'.  This commit fixes
this issue by setting 'ARCH=arm64' for aarch64 building.
Signed-off-by: Leo Yan <leo.yan@linaro.org>

build: Fix kernel header installation on ARM64

---

src/libply/aux/kallsyms.c
src/libply/provider/xprobe.c

Hello,
This PR fixes wildcard matcing for kprobe.  It failed with -22 when unsupported functions are included in the pattern.  It should check available_filter_functions in the ftrace directory and remove them.  Also make it return -2 when there's no match.
```
ply: active
^Cply: deactivating
@:
{ __x64_sys_exit+1 }: 1
{ __x64_sys_fallocate+1 }: 1
{ __x64_sys_open+1 }: 1
{ __x64_sys_newlstat+1 }: 1
{ __x64_sys_dup+1 }: 1
{ __x64_sys_sendmmsg+1 }: 1
{ __x64_sys_getdents64+1 }: 2
{ __x64_sys_pselect6+1 }: 2
{ __x64_sys_timerfd_settime+1 }: 2
{ __x64_sys_bind+1 }: 2
{ __x64_sys_ftruncate+1 }: 3
{ __x64_sys_getsockopt+1 }: 3
{ __x64_sys_clock_nanosleep+1 }: 4
{ __x64_sys_pwrite64+1 }: 4
{ __x64_sys_inotify_add_watch+1 }: 4
{ __x64_sys_accept+1 }: 4
{ __x64_sys_readlinkat+1 }: 5
{ …
```

Improve wildcard matching in k*probe

---

include/ply/func.h
include/ply/internal.h
include/ply/ply.h
include/ply/provider.h
src/libply/built-in/aggregation.c
src/libply/built-in/buffer.c
src/libply/built-in/built-in.c
src/libply/built-in/built-in.h
src/libply/built-in/flow.c
src/libply/built-in/math.c
src/libply/built-in/memory.c
src/libply/built-in/print.c
src/libply/built-in/proc.c
src/libply/libply.c
src/libply/provider.c
src/libply/provider/kprobe.c
src/libply/provider/kretprobe.c
src/libply/provider/tracepoint.c
src/ply/ply.c

Hello,
I changed the providers and built-ins to use a singly linked list to iterate them instead of having separate sections.  And for a static library, the codes need to have direct references from the main binary to be in the final image.  So I added ply_init() function to initialize the providers and built-ins explicitly.
Fixes: #68

Fix static link failure

---

man/ply.1.ronn
src/libply/built-in/aggregation.c

Add sum() function to calculate total number of some events.
```
tracepoint:syscalls/sys_exit_read { 
if (data->ret > 0)
@bytes[comm] = sum(data->ret);
}
ply: active
400+0 records in
400+0 records out
409600 bytes (410 kB, 400 KiB) copied, 0.000530946 s, 771 MB/s
ply: deactivating
@bytes:
{ ply             }: 4
{ pipewire-media- }: 64
{ gnome-terminal- }: 161
{ sh              }: 2496
{ dd              }: 413428
```

Add 'sum' function for aggregation

---

src/ply/ply.c

Replace signal() + siginterrupt() with a single call to sigaction().
This fixes following compiler warnings:
warning: ‘siginterrupt’ is deprecated: Use sigaction with SA_RESTART instead

ply: use sigaction instead of deprecated siginterrupt

---

man/ply.1.ronn

'-A' option is obsolete now.  Remove the description from the man page.
Signed-off-by: SeongJae Park <sj38.park@gmail.com>

man: remove '-A' option

---

include/ply/buffer.h
include/ply/perf_event.h
include/ply/ply.h
include/ply/provider.h
man/ply.1.ronn
src/libply/Makefile.am
src/libply/aux/perf_event.c
src/libply/built-in/buffer.c
src/libply/lexer.l
src/libply/libply.c
src/libply/provider.c
src/libply/provider/special.c
src/libply/provider/tracepoint.c
src/libply/provider/xprobe.c
src/ply/ply.c
src/ply/self-test.sh

Like awk(1) and bpftrace(8), add BEGIN and END (case-sensitive) providers to do things before and after other providers.  This can be useful to print some header message and/or set up maps to predefined values.
The way it's implemented is to use basic uprobe infra (using xprobe code).  Add two empty functions for each trigger and call it when probes are added.  But I needed to calculate (file) offsets of the functions without having an ELF parser.  So I used auxv to get ELF program header (and its virtual address).  Not sure if there's a better way but it works for me. :)
Also I added the BEGIN and END keywords as PSPEC without a colon to match with the existing convention in awk/bpftrace.
For example:
```
BEGIN {
printf("%7s  %16s  %s\n", "PID", "COMM", "FILE");
}
kprobe:__x64_sys_open { …
```

Add BEGIN and END providers

---

include/ply/internal.h
include/ply/perf_event.h
include/ply/ply.h
man/ply.1.ronn
src/libply/Makefile.am
src/libply/aux/perf_event.c
src/libply/built-in/built-in.c
src/libply/built-in/memory.c
src/libply/built-in/print.c
src/libply/grammar.y
src/libply/libply.c
src/libply/provider.c
src/libply/provider/interval.c
src/libply/type.c
src/ply/self-test.sh
test/test.sh

Hello!
The interval provider is for something needs to be done periodically.  I think  the most common usecase is to print maps and optionally clear them.  So I added it as well like below:
```
kretprobe:vfs_read {
@r["bytes"] = quantize(retval);
}
interval:s:1 {
print(@r);
clear(@r);
}
...
```
The syntax of the interval is same as bpftrace and users need to specify unit and time.  To handle maps (and aggregations) in the print and clear function, I added a new MAPREF (map reference) type.  The functions will rewrite a map argument to a map reference to pass a map fd.

Add 'interval' provider

---

include/ply/ply.h
include/ply/provider.h
include/ply/syscall.h
src/libply/arch/riscv64.c
src/libply/aux/syscall.c
src/libply/built-in/memory.c
src/libply/ir.c
src/libply/libply.c
src/libply/provider/special.c
src/libply/provider/tracepoint.c
src/ply/ply.c

Add riscv64 support in ply, and makes BEGIN/END probes more reliable by implementing BPF_PROG_TYPE_RAW_TRACEPOINT probes and then calling BPF_PROG_TEST_RUN on them.
Tested on x86 and riscv64, and it works fine.
Resolves #81. Please take a look, thanks. @wkz @namhyung
Signed-off-by: Mingzheng Xing xingmingzheng@iscas.ac.cn

ply: Initial support for riscv64

---

src/libply/arch/mips.c
src/ply/self-test.sh

These are fixes for some issues I noticed first building and testing on mips arch under OpenWrt. I'll add any more as I come across them. Please review or comment.
The MIPS64 fix suggests a future test-case checking for argument access would be useful e.g. arg5 on mips64.
And thanks again for `ply`; it's wonderful having this for embedded systems...

mips: small fixes for self-tests and mips64 ABI

---

include/ply/perf_event.h
man/ply.1.ronn
src/libply/Makefile.am
src/libply/aux/perf_event.c
src/libply/provider.c
src/libply/provider/profile.c
test/rootfs/lib/ply/test.sh

The profile provider supports profiling by allowing the user to specify how many times it will fire pre-second. Values of 1-1000 are supported, and the profile provider supports two probe formats as it's original implementation commit 12b8ca298699("profile provider support").
* profile:[N]hz: Profile on all CPUs N times per second
* profile:[C]:[N]hz: Profile on CPU C N times per second
Test this changes with 4 cores x86-64 PC as below.
```
$ sudo ./ply 'profile:2:100hz { @[cpu]=count(); } i:1s { print(@); }' 
@:
{  2 }: 100
@:
{  2 }: 200
@:
{  2 }: 300
$ sudo ./ply 'profile:100hz { @[cpu]=count(); } i:1s { print(@); }' 
@:
{  0 }: 100
{  1 }: 100
{  2 }: 100
{  3 }: 100
@:
{  0 }: 200
{  1 }: 200
{  2 }: 200
{  3 }: 200
@:
{  0 }: 300
{  1 }: 300
{  2 }: 300
{  3 }: 300
```
Change-Id: …

provider: add 'profile' provider

---

src/libply/ir.c

As entries are allocated on the stack the stack pointer is decremented and then adjusted to meet the requested alignment requirements. The current math does unfortunately not always provide the requested alignment.
One example is when the stack pointer is at -1 and an allocation of 4 bytes with alignment of 4 is performed, which results in an allocation at offset -6. A typical case where this happens is when working with tracepoints containing boolean fields.
Update the adjustment to properly round the stack pointer down to the requested alignment.
Fixes #91

ply: Correct alignment of stack allocations

---

src/libply/Makefile.am
src/libply/arch/loongarch64.c

Reference arm architecture adapted loongarch, and tested locally. loongarch technical links are as follows: [https://github.com/loongson/la-asm-manual/releases/tag/release-1.1](url)

Add support for loongarch
